### ISSUE TITLE
Rate limit

### ISSUE THREAD

**Issue by lume-code** [nero-angela/arb-translator#15]
Hello,
Great extension, thanks for the effort put into this,

There is a small issue I have encountered for larger datasets. When I ask the extension to translate 100 rows into 10 languages, it does the first language and then shows a `Failed to establish a socket connection to proxies:` and fails to do another one after that, I come back after a while and then I can do another one.
This is the same for both paid and free translation.

**Comment by nero-angela** [comment]
Hello @manlyman29

If you can share the error log of `output` → `arb-translator`, it will help improve the problem.
Also, please check if there is a limit on Google Translator API calls.

Thank you :)

**Comment by lume-code** [comment]
The Google translator API doesn't seem to have a limitation. I tried a few different keys, and all same result.

In v1.3.8 I get the below message after a few translations being done:
Translation failed : Failed to establish a socket connection to proxies: ["PROXY 127.0.0.1:1082"]
Error: Translation failed : Failed to establish a socket connection to proxies: ["PROXY 127.0.0.1:1082"]

and in the recently released v1.3.9, I get the below message and it doesn't translate anything:
Translation failed : connect ECONNREFUSED 127.0.0.1:80
Error: Translation failed : connect ECONNREFUSED 127.0.0.1:80

Thanks,

**Comment by nero-angela** [comment]
> The Google translator API doesn't seem to have a limitation. I tried a few different keys, and all same result.
> 
> In v1.3.8 I get the below message after a few translations being done: Translation failed : Failed to establish a socket connection to proxies: ["PROXY 127.0.0.1:1082"] Error: Translation failed : Failed to establish a socket connection to proxies: ["PROXY 127.0.0.1:1082"]
> 
> and in the recently released v1.3.9, I get the below message and it doesn't translate anything: Translation failed : connect ECONNREFUSED 127.0.0.1:80 Error: Translation failed : connect ECONNREFUSED 127.0.0.1:80
> 
> Thanks,

The issue has been fixed and distributed in version 1.3.10 :)

**Comment by lume-code** [comment]
Thanks, Appreciate it.

**Comment by nero-angela** [comment]
@manlyman29  As Metadata and Changelog translation functions were added in version 2.0.0, the name of the extension was changed from `ARB Translator` to [Flutter Translator](https://marketplace.visualstudio.com/items?itemName=DevStory.flutter-translator). Please refer to the [link](https://github.com/devstory-co-kr/flutter-translator/blob/main/CHANGELOG.md) for changes in version 2.0.0.

Since the unique identifier of the extension cannot be changed, it was newly released under the name [Flutter Translator](https://marketplace.visualstudio.com/items?itemName=DevStory.flutter-translator) and the repository was also moved to [devstory-co-kr/flutter-translator](https://github.com/devstory-co-kr/flutter-translator).

ARB Translator is no longer in service and this repository will not be updated, so please use the [Flutter Translator](https://marketplace.visualstudio.com/items?itemName=DevStory.flutter-translator) extension.
Thanks :)

**Comment by lume-code** [comment]
@nero-angela Thanks, Well noted.
